on: push

jobs:
  studio:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [you, mistral]
    environment: ${{matrix.platform}}
    env:
      API_KEY: ${{secrets.API_KEY}}
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest ${{matrix.platform}}_test.py
          tests: py/tests
          extras: ${{matrix.platform}}

  langgraph:
    runs-on: ubuntu-latest
    environment: openrouter
    env:
      API_KEY: ${{secrets.API_KEY}}
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest langchain_test.py
          tests: py/tests
          extras: langchain
          version: 3.12
  alicloud:
    runs-on: ubuntu-latest
    environment: alicloud
    strategy:
      matrix:
        version: [ 3.12, latest ]
    env:
      API_KEY: ${{secrets.API_KEY}}
      AGENTBAY_API_KEY: ${{secrets.AGENTBAY_API_KEY}}
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest ali_test.py
          tests: py/tests
          extras: ali
          version: ${{matrix.version}}